### ISSUE TITLE
feature request: support new syntax for uncertain metadata

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/core-validate-commit#23]
Refs: https://github.com/joyeecheung/node-core-utils/pull/72#pullrequestreview-74269096

If the tool generating the metadata is not sure about something, it can put a `?` before the metadata, and let `core-validate-commit` complain. For example, if someone LGTM via comments, the tool can generate the reviewer as:

```
?Reviewed-By: someone <mail@email.com>
```

**Comment by joyeecheung** [comment]
cc @nodejs/automation see if anyone is interested in picking this one up. This would need an update in `lib/rules/reviewers.js` and an update in https://github.com/git-lint/gitlint-parser-node as well (because that's where the context comes from)

**Comment by riyadhalnur** [comment]
I'll pick it up/_
