### ISSUE TITLE
Lines with long URLs

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/core-validate-commit#24]
Should we alleviate the 72 characters rule for lines with long URLs?

Example: https://github.com/nodejs/node/pull/17107

**Comment by Tiriel** [comment]
Well, AFAIC I'd say yes, it does seem logical otherwise the link will be broken, but I think it should first be discussed as meta in core, or wherever the contribution guides are discussed. 

I don't think that's quite up to us to decide to change the validation rules on our own.

**Comment by vsemozhetbyt** [comment]
Core issue: https://github.com/nodejs/node/issues/17116

**Comment by vsemozhetbyt** [comment]
@Tiriel Exception approved and landed: https://github.com/nodejs/node/pull/20207
