### ISSUE TITLE
What is the valid subsystem for a file that is at the root of the repo?

### ISSUE THREAD

**Issue by cclauss** [nodejs/core-validate-commit#39]
Which subsystem is [__./configure.py__](https://github.com/nodejs/node/blob/master/configure.py) in?  Should there be a __root__ subsystem?

**Comment by cclauss** [comment]
@refack

**Comment by refack** [comment]
`build,meta`

**Comment by targos** [comment]
I'd put `./configure.py` in the `build` subsystem.

To get inspiration for subsystem of a file, I recommend to use `git log --oneline -- path/to/file` and see what is the most used one.
