### ISSUE TITLE
Enable codecov?

### ISSUE THREAD

**Issue by richardlau** [nodejs/core-validate-commit#57]
The project used to use `coveralls` until it was moved into the `nodejs` organization upon which it stopped working.

It seems the approved coverage tool in the organization is `Codecov` (used by [nodejs/citgm](https://github.com/nodejs/citgm) and [nodejs/node-core-utils](https://github.com/nodejs/node-core-utils). Should we enable that for this repo?

**Comment by joyeecheung** [comment]
<img width="513" alt="Screen Shot 2019-04-16 at 5 06 35 PM" src="https://user-images.githubusercontent.com/4299420/56196755-06e54780-606a-11e9-951d-c54917bf76ab.png">

I've authorized Codecov to access this repo

**Comment by joyeecheung** [comment]
To enable codecov we need something like this

https://github.com/nodejs/node-core-utils/blob/873b22ee9c4a2101f9a31a2759013ae0fccebfd1/package.json#L16-L18

**Comment by richardlau** [comment]
> 
> 
> To enable codecov we need something like this
> 
> https://github.com/nodejs/node-core-utils/blob/873b22ee9c4a2101f9a31a2759013ae0fccebfd1/package.json#L16-L18

I'll take a look later today.

**Comment by richardlau** [comment]
PR: https://github.com/nodejs/core-validate-commit/pull/59
