### ISSUE TITLE
List available subsystems

### ISSUE THREAD

**Issue by lholmquist** [nodejs/core-validate-commit#66]
Sort of related to #58, but this command would list the available subsystems to choose from.  

When i was creating a Node core PR, i got a validation error because i used a subsystem that wasn't defined, then i had to go into the code of this repo to find the available ones.

Having the ability to list those values from the core-validate-commit tool would have been nice.

I not sure how the command might look though. maybe something like

`core-validate-commit --list subsystem` or something

I'm more than happy to work on getting a PR ready for discussion

**Comment by richardlau** [comment]
> I'm more than happy to work on getting a PR ready for discussion

Go for it 😁.
